project_new/news/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('',         views.PostList.as_view()),
    path('<int:pk>', views.PostDetail.as_view()),
    path('search/',  views.PostSearch.as_view()),

    path('article/create/', views.CreatePost.as_view()),
    path('create/',         views.CreateNews.as_view()),

    path('<int:pk>/update/', views.UpdatePost.as_view()),

    path('<int:pk>/delete/', views.DeletePost.as_view()),
]

project_new/project/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

project_new/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum

class Author(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  rating = models.IntegerField(default=0)

  class Meta:
    verbose_name = 'Автор'
    verbose_name_plural = 'Авторы'
  
  def update_rating(self):
    self.rating = Post.objects.filter(author_id=self.id).aggregate(Sum('rating'))['rating__sum']*3 + \
      Comment.objects.filter(user_id=self.user.id).aggregate(Sum('rating'))['rating__sum'] + \
      Comment.objects.filter(post_id__in=[q['id'] for q in Post.objects.filter(author_id=self.id).values('id')]).aggregate(Sum('rating'))['rating__sum']
    self.save()

  def __str__(self):
    return self.user.username

class Category(models.Model):
  name = models.TextField(unique=True)

  class Meta:
    verbose_name = 'Категория'
    verbose_name_plural = 'Категории'

  def __str__(self):
    return self.name

class Post(models.Model):
  author = models.ForeignKey(Author, on_delete=models.CASCADE)
  isnews = models.BooleanField(default=False)
  created = models.DateTimeField(auto_now_add=True)
  categories = models.ManyToManyField(Category, through='PostCategory')
  title = models.CharField(max_length=64)
  text = models.CharField(max_length=4096)
  rating = models.IntegerField(default=0)
  
  class Meta:
    verbose_name = 'Новость'
    verbose_name_plural = 'Новости'

  def preview(self):
    return (self.text[:20] + '...') if len(self.text) > 20 else self.text
  
  def like(self):
    self.rating += 1
    self.save()

  def dislike(self):
    self.rating -= 1
    self.save()

  def __str__(self):
    return self.title

class PostCategory(models.Model):
  post = models.ForeignKey(Post, on_delete=models.CASCADE)
  category = models.ForeignKey(Category, on_delete=models.CASCADE)
 
  class Meta:
    verbose_name = 'Категория новости'
    verbose_name_plural = 'Категории новостей'

  def __str__(self):
    return f'{self.post} ({self.category})'

class Comment(models.Model):
  post = models.ForeignKey(Post, on_delete=models.CASCADE)
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  text = models.CharField(max_length=4096)
  created = models.DateTimeField(auto_now_add=True)
  rating = models.IntegerField(default=0)

  class Meta:
    verbose_name = 'Комментарий'
    verbose_name_plural = 'Комментарии'

  def like(self):
    self.rating += 1
    self.save()

  def dislike(self):
    self.rating -= 1
    self.save()

  def __str__(self):
    return f'{self.user.username} про "{self.post}"'

project_new/news/forms.py
from django import forms
from .models import Post

class CreatePostForm(forms.ModelForm):
  class Meta:
    model = Post
    fields = [
      'author',
      'title',
      'text',
      'categories'
    ]

project_new/news/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from news.filters import PostFilter
from .forms import CreatePostForm
from .models import Post


class PostList(ListView):
    # Указываем модель, объекты которой мы будем выводить
    model = Post
    # Поле, которое будет использоваться для сортировки объектов
    ordering = '-created'
    # Указываем имя шаблона, в котором будут все инструкции о том,
    # как именно пользователю должны быть показаны наши объекты
    template_name = 'postlist.html'
    # Это имя списка, в котором будут лежать все объекты.
    # Его надо указать, чтобы обратиться к списку объектов в html-шаблоне.
    context_object_name = 'posts'

    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Добавляем в контекст объект фильтрации.
        context['filterset'] = self.filterset
        return context


class PostSearch(ListView):
    # Указываем модель, объекты которой мы будем выводить
    model = Post
    # Поле, которое будет использоваться для сортировки объектов
    ordering = '-created'
    # Указываем имя шаблона, в котором будут все инструкции о том,
    # как именно пользователю должны быть показаны наши объекты
    template_name = 'search.html'
    # Это имя списка, в котором будут лежать все объекты.
    # Его надо указать, чтобы обратиться к списку объектов в html-шаблоне.
    context_object_name = 'posts'

    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Добавляем в контекст объект фильтрации.
        context['filterset'] = self.filterset
        return context


class PostDetail(DetailView):
    model = Post
    template_name = 'post.html'
    context_object_name = 'post'


class CreatePost(CreateView):
    form_class = CreatePostForm
    model = Post
    template_name = 'create_post.html'

    def form_valid(self, form):
        post = form.save(commit=False)
        post.isnews = False
        return super().form_valid(form)


class CreateNews(CreateView):
    form_class = CreatePostForm
    model = Post
    template_name = 'create_news.html'

    def form_valid(self, form):
        post = form.save(commit=False)
        post.isnews = True
        return super().form_valid(form)


class UpdatePost(UpdateView):
    form_class = CreatePostForm
    model = Post
    template_name = 'edit_post.html'


class DeletePost(DeleteView):
    model = Post
    template_name = 'delete_post.html'
    success_url = reverse_lazy('post_list')

project_new/news/templates/create_news.html
{% extends 'default.html' %} 
{% load custom_filters %}
{% load custom_tags %}
{% block title %}Написать новость{% endblock title %}
{% block content %}
<h1>Написать новость</h1>
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Написать" />
</form>
{% endblock content %}

project_new/news/templates/create_post.html
{% extends 'default.html' %} 
{% load custom_filters %}
{% load custom_tags %}
{% block title %}Написать статью{% endblock title %}
{% block content %}
<h1>Написать статью</h1>
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Написать" />
</form>
{% endblock content %}

project_new/news/templates/default.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{%block title%}{%endblock title%}</title>
        <!-- Favicon-->
        <!--link rel="icon" type="image/x-icon" href="assets/favicon.ico" /-->
        <!-- Core theme CSS (includes Bootstrap)-->
		{% load static %}
		{% load custom_filters %}
		{% load custom_tags %}
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
			<div class="container">
				<button class="navbar-toggler" type="button" data-toggle="collapse"
					   data-target="#navbarResponsive"
					   aria-controls="navbarResponsive" aria-expanded="false"
					   aria-label="Toggle navigation">
				   <span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarResponsive">
				   <ul class="navbar-nav ml-auto">
					   <li class="nav-item active">
						   <a class="nav-link" href="/news">Новости на {% now %}</a>
					   </li>
					</ul>
				</div>
			</div>
		</nav>
		<div class="container">
		   <div class="row">
			   <div class="col-lg-12 text-center">
				   {% block content %}
				   {% endblock content %}
			   </div>
		   </div>
		</div>
	</body>
</html>

project_new/news/templates/delete_post.html
{% extends 'default.html' %}
{% block content %}
<h1>Удаление</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ post.title }}"?</p>
    <a href="/news/{{post.id}}">Не удалять</a>
    <input type="submit" value="Удалить" />
</form>
{% endblock content %}

project_new/news/templates/edit_post.html
{% extends 'default.html' %} 
{% load custom_filters %}
{% load custom_tags %}
{% block title %}Редактировать статью{% endblock title %}
{% block content %}
<h1>Редактировать статью</h1>
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Сохранить" />
</form>
{% endblock content %}

project_new/news/templates/post.html
{% extends 'default.html' %} 
{% load custom_filters %}
{% load custom_tags %}
{% block title %}{{post.title|censor}}{% endblock title %}
{% block content %}
<h1>{{post.title|censor}}</h1>
<p>{{post.author.user.username}}</p>
<p>{{post.created|date:'d.m.Y'}}</p>
<p>{{post.text|censor}}</p>
</hr>
<table cellpadding="12">
    <tr class=title>
        <td>Дата</td>
        <td>Рейтинг</td>
        <td>Автор</td>
        <td>Комментарий</td>
    </tr>
    {% for c in post.comment_set.all %}
    <tr>
        <td>{{c.created|date:'d.m.Y'}}</td>
        <td>{{c.rating}}</td>
        <td>{{c.user.username}}</td>
        <td>{{c.text|censor}}</td>
    </tr>
    {%endfor%}
</table>

{% endblock content %}

project_new/news/templates/postlist.html
{% extends 'default.html' %} 
{% load custom_filters %}
{% load custom_tags %}
{% block title %}Новости{% endblock title %}
{% block content %}
{% if posts %}
<h1>Все новости</h1>
<table><tbody>
    <tr class=title>
        <td>Заголовок</td>
        <td>Дата</td>
        <td>Предпросмотр</td>
    </tr>
{% for p in posts %}
<tr>
    <td><a href="{{p.id}}">{{p.title|censor}}</a></td>
    <td>{{p.created|date:'d.m.Y'}}</td>
    <td>{{p.preview|censor}}</td>
</tr>
{%endfor%}
</tbody></table>
{% else %}
<h1>Новостей нет</h1>
{% endif%}
{% endblock content %}

project_new/news/templates/search.html
{% extends 'default.html' %} 
{% load custom_filters %}
{% load custom_tags %}
{% block title %}Новости{% endblock title %}
{% block content %}
<h1>Поиск новостей</h1>
<form action="" method="get">
  {{ filterset.form.as_p }}
  <input type="submit" value="Найти" />
</form>
{% if posts %}
<h1>Найденные новости</h1>
<table><tbody>
    <tr class=title>
        <td>Заголовок</td>
        <td>Дата</td>
        <td>Предпросмотр</td>
    </tr>
{% for p in posts %}
<tr>
    <td><a href="/news/{{p.id}}">{{p.title|censor}}</a></td>
    <td>{{p.created|date:'d.m.Y'}}</td>
    <td>{{p.preview|censor}}</td>
</tr>
{%endfor%}
</tbody></table>

{% if page_obj.has_previous %}
  <a href="?page=1">1</a>
  {% if page_obj.previous_page_number != 1 %}
    {% if page_obj.number != 3 %}
      ...
    {% endif %}
    <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
  {% endif %}
{% endif %}

{{ page_obj.number }}

{% if page_obj.has_next %}
  <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
  {% if paginator.num_pages != page_obj.next_page_number %}
    {% if page_obj.number != page_obj.paginator.num_pages|add:-2 %}
      ...
    {% endif %}
    <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
  {% endif %}
{% endif %}

{% else %}
<h1>Новости не найдены</h1>
{% endif%}
{% endblock content %}